CREATE TABLE event_board
(
  NUM        NUMBER,
  WRITER     VARCHAR2(100 BYTE),
  CAPTION    VARCHAR2(200 BYTE),
  CONTENT CLOB,
  IMAGEPATH  VARCHAR2(100 BYTE),
  REGDATE    DATE,
  VIEWCOUNT NUMBER,
  startRowNum NUMBER,
  endRowNum NUMBER
)

CREATE SEQUENCE event_board_SEQ