CREATE TABLE event_mp
(
  NUM        NUMBER,
  WRITER     VARCHAR2(100 BYTE)                 NOT NULL,
  TITLE      VARCHAR2(100 BYTE),
  CONTENT    VARCHAR2(2000 BYTE),  
  orgFileName  VARCHAR2(100 BYTE),
  saveFileName  VARCHAR2(100 BYTE),
  fileSize   NUMBER,
  VIEWCOUNT  NUMBER,
  REGDATE    DATE
);

CREATE SEQUENCE event_mp_SEQ;