CREATE TABLE RSCHMAIN(
  CD     VARCHAR2(4 BYTE) NOT NULL PRIMARY KEY,
  TITLE  VARCHAR2(1000 BYTE) NOT NULL,
  SDATE  DATE,
  EDATE  DATE,
  USE    VARCHAR2(2 BYTE),
  RDATE  TIMESTAMP(6),
  COMM1   VARCHAR2(300 BYTE),
  COMM2   VARCHAR2(300 BYTE),
  COMM3   VARCHAR2(300 BYTE),
  COMM4   VARCHAR2(300 BYTE),
  COMM5   VARCHAR2(300 BYTE),
  COMM6   VARCHAR2(300 BYTE),
  CNT    NUMBER
);