CREATE TABLE RSCHMAIN
(
  CD     VARCHAR2(4 BYTE)                       NOT NULL,
  TITLE  VARCHAR2(1000 BYTE)                    NOT NULL,
  SDATE  DATE,
  EDATE  DATE,
  USE    VARCHAR2(2 BYTE),
  RDATE  TIMESTAMP(6),
  COMM   VARCHAR2(300 BYTE),
  CNT    NUMBER
)